version: "2"
services:
  server:
    image: pbl2_nuvem
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1853:1853/tcp"
      - "1873:1873/tcp"
    network_mode: "bridge"