from typing import Final

REGION_1: Final = 1
REGION_2: Final = 2
REGION_3: Final = 3

DEFAULT_RECV_TCP_BYTES: Final = 1024

BROKER_REGION_1_ADDR: Final = "localhost"
BROKER_REGION_1_PORT: Final = 1883

BROKER_REGION_2_ADDR: Final = "localhost"
BROKER_REGION_2_PORT: Final = 1883

BROKER_REGION_3_ADDR: Final = "localhost"
BROKER_REGION_3_PORT: Final = 1883
  
GAS_STATION_TIME_TO_SEND: Final = 7
GAS_STATION_TIME_TO_REFRESH: Final = 90
EDGE_TIME_TO_SEND: Final = 10
